ERROR: POST user/id/gadgets admin
[18/02/2008 16:32:37] u'ERROR: Falta un atributo en el elemento Property'
ERROR: POST user/id/gadgets admin
[18/02/2008 16:32:51] u'ERROR: Falta un atributo en el elemento Property'
ERROR: POST user/id/gadgets admin
[18/02/2008 16:35:13] u'ERROR: Falta un atributo en el elemento Property'
ERROR: POST user/id/gadgets admin
[18/02/2008 16:35:41] u'ERROR: Falta un atributo en el elemento Property'
ERROR: POST user/id/gadgets admin
[18/02/2008 16:36:32] u'ERROR: Missing attribute at Property element'
ERROR: POST user/id/resources admin
[18/02/2008 16:41:47] ERROR:  llave duplicada viola restricción unique «resource_gadgetresource_short_name_key»

INSERT INTO "resource_gadgetresource" ("short_name","vendor","version","added_by_user_id","author","mail","description","size","license","gadget_uri","creation_date","image_uri","wiki_page_uri","template_uri") VALUES ('AlarmPanel','Morfeo','1.2',1,'fabio','fabio@tid.es','Este gadget presenta el panel de alarmas',NULL,NULL,NULL,'2008-02-18 16:41:47.760397','http://demo.wasup.morfeo-project.org:8080/gadgets/images/AttentionSZ.jpg','http://forge.morfeo-project.org/wiki/index.php/Plataforma_WASUP','http://mac/~mike/guardarTexto2.xml')
ERROR: POST user/id/gadgets admin
[18/02/2008 16:53:14] <urlopen error (110, 'Connection timed out')>
ERROR: POST user/id/resources admin
[18/02/2008 17:00:23] ERROR:  llave duplicada viola restricción unique «resource_gadgetresource_short_name_key»

INSERT INTO "resource_gadgetresource" ("short_name","vendor","version","added_by_user_id","author","mail","description","size","license","gadget_uri","creation_date","image_uri","wiki_page_uri","template_uri") VALUES ('AlarmPanel','Morfeo','1.2',1,'fabio','fabio@tid.es','Este gadget presenta el panel de alarmas',NULL,NULL,NULL,'2008-02-18 17:00:23.097250','http://demo.wasup.morfeo-project.org:8080/gadgets/images/AttentionSZ.jpg','http://forge.morfeo-project.org/wiki/index.php/Plataforma_WASUP','http://mac/~mike/guardarTexto3.xml')
ERROR: POST user/id/gadgets admin
[18/02/2008 17:26:46] <urlopen error (110, 'Connection timed out')>
ERROR: POST user/id/resources admin
[19/02/2008 12:00:32] ERROR:  llave duplicada viola restricción unique «resource_gadgetresource_short_name_key»

INSERT INTO "resource_gadgetresource" ("short_name","vendor","version","added_by_user_id","author","mail","description","size","license","gadget_uri","creation_date","image_uri","wiki_page_uri","template_uri") VALUES ('Flickr','Morfeo','2.0',1,'jmostazo','jmostazo@pegaso.ls.fi.upm.es','Nueva version del gadget de flickr que permite enviar la ruta de la imagen seleccionada a un canal',NULL,NULL,NULL,'2008-02-19 12:00:32.029341','http://europa.ls.fi.upm.es/ezweb/gadgets/flickr.png','http://piccolo.ls.fi.upm.es:7000/flickr','http://europa.ls.fi.upm.es/ezweb/gadgets/flickr.xml')
ERROR: POST user/id/resources admin
[19/02/2008 12:04:45] <urlopen error (110, 'Connection timed out')>
ERROR: POST /user/admin/gadgets admin
[27/02/2008 13:04:39] El Gadget ya existe
ERROR: POST /user/admin/gadgets admin
[27/02/2008 13:05:52] El Gadget ya existe
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:47:58] TemplateHandler instance has no attribute '_flag'
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:51:00] TemplateHandler instance has no attribute '_user'
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:54:34] __init__() takes exactly 2 arguments (1 given)
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:55:22] TemplateHandler instance has no attribute '_uri'
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:56:26] __init__() takes exactly 3 arguments (2 given)
ERROR: POST /user/admin/catalogue/resource admin
[29/02/2008 12:57:31] parseString() takes at least 2 arguments (1 given)
ERROR: POST /user/admin/catalogue/resource admin
ERROR: POST /user/admin/gadgets admin
[29/02/2008 13:20:57] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[29/02/2008 13:21:18] u"ERROR: No se puede leer el c\xf3digo XHTML - global name 'GadgetCodeParser' is not defined"
ERROR: POST /user/admin/gadgets admin
[29/02/2008 13:59:03] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:22:13] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:23:08] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:34:54] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:36:56] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:48:27] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 12:51:06] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 13:23:49] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 13:23:53] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 13:23:55] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[04/03/2008 15:14:08] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[07/03/2008 11:52:11] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:22:20] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:22:59] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:23:02] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:19] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:24] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:27] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:35] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:35] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:39] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[07/03/2008 14:32:48] Gadget already exists
ERROR: POST /user/admin/gadgets admin
[31/03/2008 16:41:24] El gadget ya existe
ERROR: POST /user/admin/catalogue/resource admin
ERROR: POST /user/admin/gadgets admin
[31/03/2008 17:00:41] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[31/03/2008 17:08:24] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[31/03/2008 17:14:01] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[31/03/2008 18:31:41] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[31/03/2008 18:35:36] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[31/03/2008 18:36:10] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 09:57:19] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 11:31:02] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 11:38:54] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 11:42:14] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 11:42:52] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 14:01:51] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:31:14] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:31:25] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:35:45] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:44:10] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:45:41] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:50:12] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:52:00] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:54:05] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 15:54:49] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 16:33:07] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 16:34:19] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 16:37:15] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[01/04/2008 19:24:33] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 09:03:04] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 09:59:19] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:09] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:12] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:13] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:13] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:14] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:15] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:15] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:16] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:16] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:16] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:16] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:21] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:21] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:21] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:22] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:24] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:24] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:24] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:01:24] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:02:52] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:02:59] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:08:23] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:09:16] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:10:20] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 10:11:54] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 11:44:28] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 11:46:40] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 17:24:15] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 17:26:21] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:04:31] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:07:03] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:11:06] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:11:33] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:11:56] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:22:27] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[02/04/2008 18:29:29] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:12:28] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:13:53] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:14:58] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:26:42] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:28:29] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:30:32] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:31:21] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:31:43] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:32:33] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:33:26] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:43:18] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:43:51] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:44:43] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:45:32] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 12:47:18] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:10:14] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:10:45] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:11:11] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:22:27] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:22:32] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 13:22:37] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 15:49:39] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 15:50:00] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 15:52:44] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[03/04/2008 16:02:53] El gadget ya existe
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:09:01] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:09:19] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:10:33] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:15:43] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:16:39] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:18:25] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:19:02] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:28:58] tab cannot be created: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:37:28] tab cannot be created: invalid syntax (<string>, line 1)
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:37:37] tab cannot be created: invalid syntax (<string>, line 1)
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:42:49] tab cannot be created: global name 'tab' is not defined
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:43:12] tab cannot be created: global name 'tab' is not defined
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:54:18] tab cannot be created: global name 'Variable' is not defined
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:54:18] tab cannot be created: global name 'Variable' is not defined
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:55:12] tab cannot be created: 'dict' object has no attribute 'id'
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:55:12] tab cannot be created: 'dict' object has no attribute 'id'
ERROR: PUT /workspace/1/variables admin
[28/04/2008 17:58:43] tab cannot be created: 'dict' object has no attribute 'value'
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:13:00] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:14:09] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:14:29] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:15:07] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:16:06] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:17:54] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 13:29:49] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 15:07:45] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 15:08:45] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:11:03] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:54:09] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:54:15] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:54:16] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:54:31] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[29/04/2008 16:54:32] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[30/04/2008 10:41:08] tab cannot be created: name 'null' is not defined
ERROR: POST /workspace/1/tabs admin
[30/04/2008 11:04:12] tab cannot be created: 'tab'
ERROR: POST /workspace/1/tabs admin
[30/04/2008 11:09:13] tab cannot be created: 'tab'
ERROR: POST /workspaces admin
[30/04/2008 12:31:52] workspace cannot be created: global name 'workspace_nam' is not defined
ERROR: POST /workspaces admin
[30/04/2008 12:31:54] workspace cannot be created: global name 'workspace_nam' is not defined
ERROR: POST /workspaces admin
[30/04/2008 13:03:00] workspace cannot be created: global name 'workspace_nam' is not defined
ERROR: PUT /workspace/1/variables admin
[30/04/2008 13:05:03] tab cannot be created: name 'null' is not defined
ERROR: POST /workspaces admin
[30/04/2008 17:19:35] workspace cannot be created: global name 'workspace_nam' is not defined
ERROR: POST /workspaces admin
[30/04/2008 17:28:28] workspace cannot be created: global name 'workspace_nam' is not defined
ERROR: POST /workspace/1/tab/1/igadgets admin
[05/05/2008 12:19:19] No se pudo actualizar el IGadget: global name 'AbstractVar' is not defined
ERROR: POST /workspace/1/tab/1/igadgets admin
[05/05/2008 12:21:05] No se pudo actualizar el IGadget: global name 'AbstractVar' is not defined
ERROR: POST /workspaces admin
[05/05/2008 15:42:42] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 15:49:07] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 15:51:21] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 15:52:09] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 16:03:42] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 16:17:03] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 16:18:14] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 16:25:12] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 16:36:42] workspace cannot be created: Out matching query does not exist.
ERROR: POST /workspaces admin
[05/05/2008 17:21:03] workspace cannot be created: Out matching query does not exist.
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:01:28] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:02:09] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:09:19] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:09:21] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:09:23] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 10:13:48] tab cannot be created: name 'null' is not defined
ERROR: PUT /workspace/2/variables admin
[06/05/2008 11:14:16] tab cannot be created: name 'null' is not defined
ERROR: POST /workspace/1/tab/2/igadgets admin
[07/05/2008 11:46:59] No se pudo actualizar el IGadget: 'Variable' object is not iterable
ERROR: POST /workspace/1/tab/2/igadgets admin
[07/05/2008 12:17:25] No se pudo actualizar el IGadget: {<cursor object at 0x88809d0>: 'ERROR:  inserci\xc3\xb3n o actualizaci\xc3\xb3n en la tabla \xc2\xabconnectable_out\xc2\xbb viola la llave for\xc3\xa1nea \xc2\xabconnectable_out_variable_id_fkey\xc2\xbb\nDETAIL:  La llave (variable_id)=(52) no est\xc3\xa1 presente en la tabla \xc2\xabworkspace_abstractvariable\xc2\xbb.\n'}
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:21:17] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:21:17] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:21:35] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:21:37] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:21:37] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:48:33] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[07/05/2008 13:48:54] cannot update variables: name 'null' is not defined
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 14:08:59] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 15:59:19] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:05:16] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:16:37] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:22:27] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:35:12] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:39:06] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 16:46:28] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /user/admin/catalogue/resource admin
[07/05/2008 16:49:30] <unknown>:1:49: syntax error
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:01:00] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:05:23] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:12:38] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:52:24] No se pudo actualizar el IGadget: 'abstract_variable' is an invalid keyword argument for this function
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:56:06] No se pudo actualizar el IGadget: In matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 17:57:38] No se pudo actualizar el IGadget: In matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:00:11] No se pudo actualizar el IGadget: In matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:00:34] No se pudo actualizar el IGadget: Out matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:03:25] No se pudo actualizar el IGadget: Out matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:08:18] No se pudo actualizar el IGadget: Transaction managed block ended with pending COMMIT/ROLLBACK
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:13:11] No se pudo actualizar el IGadget: {<cursor object at 0x87f0f20>: 'ERROR:  inserci\xc3\xb3n o actualizaci\xc3\xb3n en la tabla \xc2\xabconnectable_in\xc2\xbb viola la llave for\xc3\xa1nea \xc2\xabconnectable_in_variable_id_fkey\xc2\xbb\nDETAIL:  La llave (variable_id)=(2) no est\xc3\xa1 presente en la tabla \xc2\xabigadget_variable\xc2\xbb.\n'}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:13:43] No se pudo actualizar el IGadget: Out matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:14:46] No se pudo actualizar el IGadget: {<cursor object at 0x888b700>: 'ERROR:  inserci\xc3\xb3n o actualizaci\xc3\xb3n en la tabla \xc2\xabconnectable_in\xc2\xbb viola la llave for\xc3\xa1nea \xc2\xabconnectable_in_variable_id_fkey\xc2\xbb\nDETAIL:  La llave (variable_id)=(4) no est\xc3\xa1 presente en la tabla \xc2\xabigadget_variable\xc2\xbb.\n'}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:22:51] No se pudo actualizar el IGadget: 'variable' is an invalid keyword argument for this function
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:32:57] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'abstract_variable__id': 1}
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:38:12] No se pudo actualizar el IGadget: get() returned more than one Out -- it returned 2! Lookup parameters were {'abstract_variable__id': 1}
ERROR: POST /user/admin/catalogue/resource admin
ERROR: POST /user/admin/catalogue/resource admin
[07/05/2008 18:45:19] <unknown>:1:54: syntax error
ERROR: POST /workspace/1/tab/2/igadgets admin
[07/05/2008 18:46:12] No se pudo actualizar el IGadget: Out matching query does not exist.
ERROR: POST /workspace/1/tab/1/igadgets admin
[07/05/2008 18:51:27] No se pudo actualizar el IGadget: Out matching query does not exist.
ERROR: POST /workspaces/2/wiring admin
[09/05/2008 15:43:23] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 10:25:43] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 10:41:31] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 10:42:13] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 10:42:32] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 10:43:23] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 11:23:43] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/2/wiring admin
[12/05/2008 11:36:53] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[12/05/2008 18:07:16] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[12/05/2008 18:10:35] Fallo al guardar los connectables: 'iGadgetList'
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:39] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:39] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:40] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:40] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:41] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[12/05/2008 18:10:41] cannot update variables: name 'null' is not defined
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 15:55:19] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 16:00:03] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 16:10:42] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 16:11:22] Fallo al guardar los connectables: 'iGadgetList'
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 17:55:42] Fallo al guardar los connectables: 'createdChannels'
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 17:58:47] Fallo al guardar los connectables: global name 'Abstract_Variable' is not defined
ERROR: POST /workspaces/1/wiring admin
[13/05/2008 18:00:40] Fallo al guardar los connectables: global name 'Abstract_Variable' is not defined
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 09:47:36] Fallo al guardar los connectables: 'dict' object has no attribute 'name'
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 09:49:35] Fallo al guardar los connectables: 'dict' object has no attribute 'name'
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 09:51:33] Fallo al guardar los connectables: 'dict' object has no attribute 'name'
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 13:28:29] Fallo al guardar los connectables: string indices must be integers
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 13:34:37] Fallo al guardar los connectables: string indices must be integers
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 13:46:01] Fallo al guardar los connectables: type object 'InOut' has no attribute 'objets'
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 14:06:20] Fallo al guardar los connectables: 'provisional_id'
ERROR: POST /workspaces/1/wiring admin
[14/05/2008 14:07:30] Fallo al guardar los connectables: 'provisional_id'
ERROR: POST /user/admin/gadgets admin
[19/05/2008 09:53:06] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[19/05/2008 09:57:15] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[19/05/2008 09:57:47] El gadget ya existe
ERROR: POST /user/admin/gadgets admin
[19/05/2008 10:00:46] El gadget ya existe
ERROR: PUT /workspace/1/variables admin
[19/05/2008 11:04:38] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[19/05/2008 11:04:38] cannot update variables: name 'null' is not defined
ERROR: POST /workspaces/1/wiring admin
[19/05/2008 12:31:20] Fallo al guardar los connectables: 'channelsForRemoving'
ERROR: PUT /workspace/1/variables admin
[19/05/2008 16:03:03] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[19/05/2008 16:07:02] cannot update variables: name 'null' is not defined
ERROR: PUT /workspace/1/variables admin
[19/05/2008 16:07:02] cannot update variables: name 'null' is not defined
ERROR: POST /user/admin/catalogue/resource admin
[20/05/2008 07:51:09] <unknown>:1:54: syntax error
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:38:20] Fallo al guardar los connectables: cannot fit 'long' into an index-sized integer
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:39:01] Fallo al guardar los connectables: cannot fit 'long' into an index-sized integer
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:39:31] Fallo al guardar los connectables: cannot fit 'long' into an index-sized integer
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:42:45] Fallo al guardar los connectables: cannot fit 'long' into an index-sized integer
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:47:23] Fallo al guardar los connectables: list assignment index out of range
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 11:49:05] Fallo al guardar los connectables: list indices must be integers
ERROR: POST /workspaces/1/wiring admin
[20/05/2008 16:09:07] Fallo al guardar los connectables: list indices must be integers
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:50:32] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:50:32] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:50:33] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:50:34] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:50:34] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:52:05] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:52:07] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[20/05/2008 16:52:09] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:44:31] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:44:33] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:44:35] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:45:13] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:45:15] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:45:17] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:45:18] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:46:47] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:47:08] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:47:10] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:47:16] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:47:18] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:47:19] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:54:47] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:54:52] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:54:53] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:54:53] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[21/05/2008 15:54:54] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:25:03] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:30:47] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:31:39] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:32:16] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:32:35] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:34:38] cannot update variables: Variable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 13:43:33] cannot update variables: Variable matching query does not exist.
ERROR: POST /workspaces/1/wiring admin
[22/05/2008 15:53:53] Fallo al guardar los connectables: In matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[22/05/2008 16:22:56] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:05:00] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:05:50] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:06:46] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:08:58] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:09:14] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:12:02] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:28:43] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:29:26] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:34:39] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:40:52] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:44:43] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:46:15] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:47:18] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:48:39] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:49:00] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:50:34] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:56:22] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:56:30] cannot update variables: 'id'
ERROR: PUT /workspace/1/variables admin
[23/05/2008 11:57:41] cannot update variables: 'id'
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/voting/Morfeo/Bandeja_de_Averias/1.0 admin
ERROR: POST /user/admin/catalogue/resource admin
ERROR: GET /workspaces/1 admin
[23/07/2008 12:17:51] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 224, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 311, in get_global_workspace_data
    data = serializers.serialize('python', tabs, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/django/core/serializers/__init__.py", line 67, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/django/core/serializers/base.py", line 35, in serialize
    for obj in queryset:
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 189, in iterator
    cursor.execute("SELECT " + (self._distinct and "DISTINCT " or "") + ",".join(select) + sql, params)
  File "/usr/lib/python2.5/site-packages/django/db/backends/util.py", line 18, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/django/db/backends/postgresql/base.py", line 47, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna workspace_tab.locked
LINE 1: ...,"workspace_tab"."name","workspace_tab"."visible","workspace...
                                                             ^

SELECT "workspace_tab"."id","workspace_tab"."name","workspace_tab"."visible","workspace_tab"."locked","workspace_tab"."workspace_id","workspace_tab"."abstract_variable_id" FROM "workspace_tab" WHERE ("workspace_tab"."workspace_id" = 1) ORDER BY "workspace_tab"."id" ASC

ERROR: GET /workspaces admin
[23/07/2008 12:37:49] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 177, in read
    data = serializers.serialize('python', workspaces, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/django/core/serializers/__init__.py", line 67, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/django/core/serializers/base.py", line 35, in serialize
    for obj in queryset:
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active

ERROR: GET /workspaces/1 admin
[23/07/2008 12:40:29] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 223, in read
    workspaces = get_list_or_404(WorkSpace, user=user, pk=workspace_id)
  File "/usr/lib/python2.5/site-packages/django/shortcuts/__init__.py", line 59, in get_list_or_404
    obj_list = list(queryset.filter(*args, **kwargs))
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active

ERROR: GET /workspaces/1 admin
[23/07/2008 12:41:23] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 223, in read
    workspaces = get_list_or_404(WorkSpace, user=user, pk=workspace_id)
  File "/usr/lib/python2.5/site-packages/django/shortcuts/__init__.py", line 59, in get_list_or_404
    obj_list = list(queryset.filter(*args, **kwargs))
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active

ERROR: GET /workspaces/1 admin
[23/07/2008 12:42:19] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 223, in read
    workspaces = get_list_or_404(WorkSpace, user=user, pk=workspace_id)
  File "/usr/lib/python2.5/site-packages/django/shortcuts/__init__.py", line 59, in get_list_or_404
    obj_list = list(queryset.filter(*args, **kwargs))
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active

ERROR: GET /workspaces/1 admin
[23/07/2008 12:42:59] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 223, in read
    workspaces = get_list_or_404(WorkSpace, users__id=user.id, pk=workspace_id)
  File "/usr/lib/python2.5/site-packages/django/shortcuts/__init__.py", line 59, in get_list_or_404
    obj_list = list(queryset.filter(*args, **kwargs))
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active

ERROR: POST /workspace/1/tab/1/igadgets admin
[23/07/2008 13:12:37] No se pudo actualizar el IGadget: Cannot resolve keyword 'user' into field. Choices are: users, workspacevariable, tab, id, name, active
ERROR: GET /workspaces admin
[23/07/2008 15:15:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 175, in read
    return HttpResponseBadRequest(get_xml_error(unicode(e)), mimetype='application/xml; charset=UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 29: ordinal not in range(128)

ERROR: GET /workspaces/1 admin
[23/07/2008 15:17:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 227, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 324, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d) for d in tabs_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 237, in get_workspace_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[23/07/2008 15:31:28] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d) for d in tabs_data]
TypeError: get_workspace_variable_data() takes exactly 2 arguments (1 given)

ERROR: GET /workspaces/1 admin
[23/07/2008 15:32:22] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d) for d in tabs_data]
TypeError: get_workspace_variable_data() takes exactly 2 arguments (1 given)

ERROR: GET /workspaces/1 admin
[23/07/2008 15:35:12] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d, user) for d in tabs_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 238, in get_workspace_variable_data
    variable_value = VariableValues.objects.get(abstract_variable=abstract_var)
NameError: global name 'VariableValues' is not defined

ERROR: GET /workspaces/1 admin
[23/07/2008 15:36:12] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d, user) for d in tabs_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 238, in get_workspace_variable_data
    variable_value = VariableValue.objects.get(abstract_variable=abstract_var)
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 263, in get
    raise self.model.DoesNotExist, "%s matching query does not exist." % self.model._meta.object_name
DoesNotExist: VariableValue matching query does not exist.

ERROR: GET /workspaces/1 admin
[23/07/2008 15:36:16] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d, user) for d in tabs_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 238, in get_workspace_variable_data
    variable_value = VariableValue.objects.get(abstract_variable=abstract_var)
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 263, in get
    raise self.model.DoesNotExist, "%s matching query does not exist." % self.model._meta.object_name
DoesNotExist: VariableValue matching query does not exist.

ERROR: GET /workspaces/1 admin
[23/07/2008 15:41:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 228, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 327, in get_global_workspace_data
    workspace_variables_data = get_workspace_variables_data(workSpaceDAO, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 207, in get_workspace_variables_data
    ws_variables_data = [get_workspace_variable_data(d, user) for d in tabs_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 240, in get_workspace_variable_data
    data_ret['value'] = variable_value.value
AttributeError: '_QuerySet' object has no attribute 'value'

ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 11:21:24] No se pudo actualizar el IGadget: 'value' is an invalid keyword argument for this function
ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 11:26:29] No se pudo actualizar el IGadget: global name 'VariableValue' is not defined
ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 11:38:40] No se pudo actualizar el IGadget: 'AbstractVariable' object has no attribute 'value'
ERROR: GET /workspaces/1 admin
[24/07/2008 11:39:42] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:39:52] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:39:58] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:40:06] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:40:26] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:40:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d) for d in igadget_data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 384, in get_igadget_data
    data_ret['variables'] = [get_variable_data(d) for d in data]
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 402, in get_variable_data
    data_ret['value'] = abstract_var.value
AttributeError: 'AbstractVariable' object has no attribute 'value'

ERROR: GET /workspaces/1 admin
[24/07/2008 11:47:53] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 233, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/get_data.py", line 323, in get_global_workspace_data
    igadget_data = [get_igadget_data(d, user) for d in igadget_data]
TypeError: get_igadget_data() takes exactly 1 argument (2 given)

ERROR: DELETE /workspace/1/tab/6 admin
[24/07/2008 11:49:38] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 388, in delete
    deleteTab(tab, user)
TypeError: deleteTab() takes exactly 1 argument (2 given)

ERROR: DELETE /workspace/1/tab/6 admin
[24/07/2008 12:17:52] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 388, in delete
    deleteTab(tab, user)
TypeError: deleteTab() takes exactly 1 argument (2 given)

ERROR: DELETE /workspace/1/tab/2 admin
[24/07/2008 12:18:53] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 388, in delete
    deleteTab(tab, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 76, in deleteTab
    VariableValues.objects.get(abstract_variable=tab.abstract_variable, user=user).delete();
NameError: global name 'VariableValues' is not defined

ERROR: DELETE /workspace/1/tab/1 admin
[24/07/2008 12:19:54] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 388, in delete
    deleteTab(tab, user)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 67, in deleteTab
    deleteIGadget(igadget, user)
TypeError: deleteIGadget() takes exactly 1 argument (2 given)

ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 12:24:37] No se pudo actualizar el IGadget: get_igadget_data() takes exactly 2 arguments (1 given)
ERROR: DELETE /workspace/1/tab/1/igadgets/4 admin
[24/07/2008 12:27:21] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/igadget/views.py", line 322, in delete
    deleteIGadget(igadget)
TypeError: deleteIGadget() takes exactly 2 arguments (1 given)

ERROR: DELETE /workspace/1/tab/1/igadgets/4 admin
[24/07/2008 12:28:01] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 112, in dispatch
    return target.delete(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/igadget/views.py", line 322, in delete
    deleteIGadget(igadget)
TypeError: deleteIGadget() takes exactly 2 arguments (1 given)

ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 12:28:44] No se pudo actualizar el IGadget: get_igadget_data() takes exactly 2 arguments (1 given)
ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 12:30:23] No se pudo actualizar el IGadget: get_igadget_data() takes exactly 2 arguments (1 given)
ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 12:30:43] No se pudo actualizar el IGadget: get_igadget_data() takes exactly 2 arguments (1 given)
ERROR: POST /workspace/1/tab/1/igadgets admin
[24/07/2008 12:31:35] No se pudo actualizar el IGadget: get_igadget_data() takes exactly 2 arguments (1 given)
ERROR: POST /workspaces/1/wiring admin
[24/07/2008 12:36:38] Fallo al guardar los connectables: 'value' is an invalid keyword argument for this function
ERROR: PUT /workspace/1/variables admin
[24/07/2008 12:46:04] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 109, in dispatch
    return target.update(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 429, in update
    msg = _("cannot update variables: ") + unicode(e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 17: ordinal not in range(128)

ERROR: PUT /workspace/1/variables admin
[24/07/2008 13:46:10] no se pudieron actualizar las variablesWorkSpaceVariable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[24/07/2008 13:48:06] no se pudieron actualizar las variablesWorkSpaceVariable matching query does not exist.
ERROR: PUT /workspace/1/variables admin
[24/07/2008 14:04:55] no se pudieron actualizar las variablesWorkSpaceVariable matching query does not exist.
ERROR: GET /workspace/1/link admin
[29/07/2008 09:59:03] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
AttributeError: WorkSpaceLinkerEntry instance has no attribute 'read'

ERROR: GET /workspace/1/link admin
[29/07/2008 09:59:56] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 449, in read
    return HttpResponse(json_encode(variable_data), mimetype='application/json; charset=UTF-8')
NameError: global name 'variable_data' is not defined

ERROR: GET /workspace/1/copy admin
[29/07/2008 10:00:17] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 454, in read
    workspace = get_or_404(WorkSpace, id=workspace_id)
NameError: global name 'get_or_404' is not defined

ERROR: GET /workspace/1/copy admin
[29/07/2008 10:00:53] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 456, in read
    cloned_ws = Workspace(workspace)
NameError: global name 'Workspace' is not defined

ERROR: GET /workspace/1/copy admin
ERROR: GET /workspace/1/copy admin
ERROR: GET /workspace/1/copy admin
ERROR: GET /workspace/1/copy admin
[29/07/2008 10:07:44] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 456, in read
    cloned_ws = workspace.clone()
AttributeError: 'WorkSpace' object has no attribute 'clone'

ERROR: GET /workspace/1/copy admin
[29/07/2008 10:14:45] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 456, in read
    cloned_ws = Workspace(name=workspace.name, active=False)
NameError: global name 'Workspace' is not defined

ERROR: GET /workspace/1/copy admin
[29/07/2008 10:14:48] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 456, in read
    cloned_ws = Workspace(name=workspace.name, active=False)
NameError: global name 'Workspace' is not defined

ERROR: GET /workspace/1/copy admin
[29/07/2008 10:15:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    return HttpResponse(json_encode(variable_data), mimetype='application/json; charset=UTF-8')
NameError: global name 'variable_data' is not defined

ERROR: GET /workspace/1/copy admin
[29/07/2008 11:47:35] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 460, in read
    tabs = Tabs.objects.filter(workspace=workspace)
NameError: global name 'Tabs' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 12:53:31] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 455, in read
    position_new['field.attname'] = position.attname
AttributeError: 'Position' object has no attribute 'attname'

ERROR: GET /workspace/1/link admin
[29/07/2008 12:54:20] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 455, in read
    position_new[field.attname] = position[field.attname]
AttributeError: 'Position' object has no attribute 'attname'

ERROR: GET /workspace/1/link admin
[29/07/2008 13:34:47] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 455, in read
    eval('position_new.' + field.attname + '= field.attname')
  File "<string>", line 1
    position_new.id= field.attname
                   ^
SyntaxError: invalid syntax

ERROR: GET /workspace/1/link admin
[29/07/2008 13:37:36] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 456, in read
    eval(exp)
  File "<string>", line 1
    position_new.id= field.attname
                   ^
SyntaxError: invalid syntax

ERROR: GET /workspace/1/link admin
[29/07/2008 13:38:12] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 457, in read
    eval(exp)
  File "<string>", line 1
    position_new.id= field.attname
                   ^
SyntaxError: invalid syntax

ERROR: GET /workspace/1/link admin
[29/07/2008 13:39:38] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 457, in read
    eval(exp)
  File "<string>", line 1
    position_new.id=field.attname
                   ^
SyntaxError: invalid syntax

ERROR: GET /workspace/1/link admin
[29/07/2008 13:40:40] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 458, in read
    eval(exp)
  File "<string>", line 1
    position_new.id=field.attname
                   ^
SyntaxError: invalid syntax

ERROR: GET /workspace/1/link admin
[29/07/2008 13:56:44] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 455, in read
    meta = positiion._meta
NameError: name 'positiion' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 13:57:00] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    if (field != meta.autofield):
AttributeError: 'Options' object has no attribute 'autofield'

ERROR: GET /workspace/1/link admin
[29/07/2008 14:03:13] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 461, in read
    exec(stm)
  File "<string>", line 1, in <module>
AttributeError: 'Position' object has no attribute 'attname'

ERROR: GET /workspace/1/link admin
[29/07/2008 14:07:36] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 466, in read
    exec(stm)
  File "<string>", line 1
    position_new.
                ^
SyntaxError: unexpected EOF while parsing

ERROR: GET /workspace/1/link admin
[29/07/2008 14:07:54] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 468, in read
    exec(stm)
  File "<string>", line 1
    position_new.
                ^
SyntaxError: unexpected EOF while parsing

ERROR: GET /workspace/1/link admin
[29/07/2008 14:10:01] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 468, in read
    exec(stm)
  File "<string>", line 1, in <module>
NameError: name 'pposition_new' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 14:11:48] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 460, in read
    stm = "%s.%s = %s.%s" % 'position_new', field.attname, position, field.attname
TypeError: not enough arguments for format string

ERROR: GET /workspace/1/link admin
[29/07/2008 14:15:24] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 469, in read
    return HttpResponse(json_encode(variable_data), mimetype='application/json; charset=UTF-8')
NameError: name 'variable_data' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 14:16:11] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 469, in read
    return HttpResponse(json_encode(variable_data), mimetype='application/json; charset=UTF-8')
NameError: name 'variable_data' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 15:36:58] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 473, in read
    cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 66, in cloneTuple
    meta = tuple._meta
AttributeError: '_QuerySet' object has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[29/07/2008 15:37:37] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 471, in read
    workspace = WorkSpace.objects.get_object_or_404(id=workspace_id)
AttributeError: 'Manager' object has no attribute 'get_object_or_404'

ERROR: GET /workspace/1/link admin
[29/07/2008 15:38:09] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 471, in read
    workspace = WorkSpace.objects.get_object_or_404(id=workspace_id)
AttributeError: 'Manager' object has no attribute 'get_object_or_404'

ERROR: GET /workspace/1/link admin
[29/07/2008 15:39:09] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 473, in read
    cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 67, in cloneTuple
    model = _meta.jiki
NameError: name '_meta' is not defined

ERROR: GET /workspace/1/link admin
[29/07/2008 15:43:18] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 473, in read
    cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 67, in cloneTuple
    model_name = _meta.object_name
NameError: name '_meta' is not defined

ERROR: GET /workspace/1/link admin
[30/07/2008 09:43:57] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
TypeError: cloneTuple() takes exactly 1 argument (2 given)

ERROR: GET /workspace/1/link admin
[30/07/2008 09:44:20] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 9, in cloneTuple
    model = eval(model_name)
  File "<string>", line 1, in <module>
NameError: name 'WorkSpace' is not defined

ERROR: GET /workspace/1/link admin
[30/07/2008 10:54:53] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 42, in cloneTuple
    new_id = self.getMapping(table_name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 33, in getMapping
    return self.mapping.getMapping(table_name, old_id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 8, in getMapping
    mapping = self.tables[table_name]
KeyError: 'WorkSpace'

ERROR: GET /workspace/1/link admin
[30/07/2008 10:56:08] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 42, in cloneTuple
    new_id = self.getMapping(table_name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 33, in getMapping
    return self.mapping.getMapping(table_name, old_id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 8, in getMapping
    mapping = self.tables[table_name]
KeyError: 'WorkSpace'

ERROR: GET /workspace/1/link admin
[30/07/2008 11:01:04] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 64, in cloneTuple
    self.addMapping(table_name, tuple.id, cloned_tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 39, in addMapping
    return self.mapping.addMapping(table_name, old_id. new_id)
AttributeError: 'int' object has no attribute 'new_id'

ERROR: GET /workspace/1/link admin
[30/07/2008 11:01:22] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 64, in cloneTuple
    self.addMapping(table_name, tuple.id, cloned_tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 39, in addMapping
    return self.mapping.addMapping(table_name, old_id. new_id)
AttributeError: 'int' object has no attribute 'new_id'

ERROR: GET /workspace/1/link admin
[30/07/2008 12:19:25] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 78, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 47, in cloneTuple
    new_id = self.getMapping(table_name, tuple.id)
AttributeError: type object 'Tab' has no attribute 'id'

ERROR: GET /workspace/1/link admin
[30/07/2008 12:23:47] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 78, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 47, in cloneTuple
    new_id = self.getMapping(table_name, tuple.id)
AttributeError: type object 'Tab' has no attribute 'id'

ERROR: GET /workspace/1/link admin
[30/07/2008 13:39:34] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 76, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 44, in cloneTuple
    meta = tuple._meta
AttributeError: 'RelatedObject' object has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[30/07/2008 14:38:49] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 76, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 44, in cloneTuple
    meta = tuple._meta
AttributeError: 'RelatedObject' object has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[30/07/2008 14:46:33] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 76, in cloneTuple
    related_tuple = related_table.model
NameError: name 'related_table' is not defined

ERROR: GET /workspace/1/link admin
[30/07/2008 15:07:12] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 90, in cloneTuple
    related_tuple = self.get_tuple(related_table_name, related_table.field.attname, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 48, in get_tuple
    exec(stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 261, in get
    obj_list = list(clone)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'workspace_id' into field. Choices are: igadget, id, name, visible, locked, workspace, abstract_variable

ERROR: GET /workspace/1/link admin
[30/07/2008 15:08:45] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 90, in cloneTuple
    related_tuple = self.get_tuple(related_table_name, related_table.field.name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 48, in get_tuple
    exec(stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 264, in get
    assert len(obj_list) == 1, "get() returned more than one %s -- it returned %s! Lookup parameters were %s" % (self.model._meta.object_name, len(obj_list), kwargs)
AssertionError: get() returned more than one Tab -- it returned 3! Lookup parameters were {'workspace': 1}

ERROR: GET /workspace/1/link admin
[30/07/2008 15:30:50] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 94, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 75, in cloneTuple
    stm = "%s.%s.id = %s" % ('cloned_tuple', field.name, self.getMapping(related_table_name, tuple.workspace.id))
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 38, in getMapping
    return self.mapping.getMapping(table_name, old_id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 18, in getMapping
    new_id = mapping[odl_id]
NameError: global name 'odl_id' is not defined

ERROR: GET /workspace/1/link admin
ERROR: GET /workspace/1/link admin
[30/07/2008 15:39:51] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 97, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 72, in cloneTuple
    exec(stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/fields/related.py", line 167, in __get__
    raise self.field.rel.to.DoesNotExist
DoesNotExist

ERROR: GET /workspace/1/link admin
[30/07/2008 15:41:23] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 97, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 72, in cloneTuple
    exec(stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/fields/related.py", line 167, in __get__
    raise self.field.rel.to.DoesNotExist
DoesNotExist

ERROR: GET /workspace/1/link admin
[30/07/2008 15:47:54] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 108, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 83, in cloneTuple
    exec(stm)
  File "<string>", line 1
    cloned_tuple.workspace = 39 MyWorkSpace
                                          ^
SyntaxError: unexpected EOF while parsing

ERROR: GET /workspace/1/link admin
[30/07/2008 15:50:00] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 108, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 79, in cloneTuple
    cloned_related_object = self.get_related_tuple(related_table_name, cloned_related_object_id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 55, in get_related_tuple
    tuple = model.objects.get(id=tuple_id)
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 263, in get
    raise self.model.DoesNotExist, "%s matching query does not exist." % self.model._meta.object_name
DoesNotExist: AbstractVariable matching query does not exist.

ERROR: GET /workspace/1/link admin
[30/07/2008 16:10:56] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 84, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple)
TypeError: get_related_tuple() takes exactly 3 arguments (4 given)

ERROR: GET /workspace/1/link admin
[30/07/2008 16:17:40] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 84, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple)
TypeError: get_related_tuple() takes exactly 3 arguments (4 given)

ERROR: GET /workspace/1/link admin
[30/07/2008 16:19:05] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 84, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple)
TypeError: get_related_tuple() takes exactly 3 arguments (4 given)

ERROR: GET /workspace/1/link admin
[30/07/2008 16:19:30] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 84, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple)
TypeError: get_related_tuple() takes exactly 3 arguments (4 given)

ERROR: GET /workspace/1/link admin
[30/07/2008 16:21:09] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 114, in cloneTuple
    for related_tuple in related_tuples:
TypeError: 'type' object is not iterable

ERROR: GET /workspace/1/link admin
[30/07/2008 16:22:29] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 86, in cloneTuple
    cloned_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 67, in cloneTuple
    meta = tuple._meta
AttributeError: type object 'tuple' has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[30/07/2008 16:23:32] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 86, in cloneTuple
    cloned_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 67, in cloneTuple
    meta = tuple._meta
AttributeError: type object 'tuple' has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[30/07/2008 16:26:40] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 115, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 86, in cloneTuple
    cloned_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 67, in cloneTuple
    meta = tuple._meta
AttributeError: type object 'tuple' has no attribute '_meta'

ERROR: GET /workspace/1/link admin
[30/07/2008 16:33:43] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 117, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 86, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 64, in get_related_tuple
    exec (stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 261, in get
    obj_list = list(clone)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'workspace' into field. Choices are: users, tab, workspacevariable, id, name, active

ERROR: GET /workspace/1/link admin
[30/07/2008 16:42:34] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 117, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 86, in cloneTuple
    related_tuple = self.get_related_tuple(related_table_name, field.name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 64, in get_related_tuple
    exec (stm)
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/django/db/models/manager.py", line 69, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 261, in get
    obj_list = list(clone)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 114, in __iter__
    return iter(self._get_data())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 482, in _get_data
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 180, in iterator
    select, sql, params = self._get_sql_clause()
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 497, in _get_sql_clause
    joins2, where2, params2 = self._filters.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 719, in get_sql
    joins2, where2, params2 = val.get_sql(opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 770, in get_sql
    return parse_lookup(self.kwargs.items(), opts)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 925, in parse_lookup
    joins2, where2, params2 = lookup_inner(path, lookup_type, value, opts, opts.db_table, None)
  File "/usr/lib/python2.5/site-packages/django/db/models/query.py", line 1043, in lookup_inner
    raise TypeError, "Cannot resolve keyword '%s' into field. Choices are: %s" % (name, ", ".join(choices))
TypeError: Cannot resolve keyword 'workspace' into field. Choices are: users, tab, workspacevariable, id, name, active

ERROR: GET /workspace/1/link admin
[30/07/2008 16:57:23] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 130, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 97, in cloneTuple
    fk_id = self.get_tuple_fk(tuple, field_name)
NameError: name 'field_name' is not defined

ERROR: GET /workspace/1/link admin
[30/07/2008 16:57:58] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 130, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 97, in cloneTuple
    fk_id = self.get_tuple_fk(tuple, field.name)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 47, in get_tuple_fk
    exec(stm)
  File "<string>", line 1, in <module>
AttributeError: 'Tab' object has no attribute 'fk_field'

ERROR: GET /workspace/1/link admin
[30/07/2008 17:01:07] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 127, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 98, in cloneTuple
    cloned_tuple = self.cloneTuple(related_tuple)
UnboundLocalError: local variable 'related_tuple' referenced before assignment

ERROR: GET /workspace/1/link admin
[30/07/2008 17:02:06] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 127, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 98, in cloneTuple
    cloned_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 84, in cloneTuple
    return self.get_tuple(table_name, new_id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 53, in get_tuple
    tuple = model.filter.get(id=tuple_id)
AttributeError: type object 'WorkSpace' has no attribute 'filter'

ERROR: GET /workspace/1/link admin
[30/07/2008 17:08:35] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 125, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 96, in cloneTuple
    cloned_related_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 122, in cloneTuple
    related_tuples = self.get_related_tuples(related_table_name, related_table.field.name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 58, in get_related_tuples
    model = eval(table_name)
  File "<string>", line 1, in <module>
NameError: name 'Out' is not defined

ERROR: GET /workspace/1/link admin
[30/07/2008 17:12:52] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 127, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 98, in cloneTuple
    cloned_related_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 124, in cloneTuple
    related_tuples = self.get_related_tuples(related_table_name, related_table.field.name, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 60, in get_related_tuples
    model = eval(table_name)
  File "<string>", line 1, in <module>
NameError: name 'Out' is not defined

ERROR: GET /workspace/1/link admin
ERROR: GET /workspace/1/link admin
ERROR: GET /workspace/1/link admin
ERROR: GET /workspace/1/link admin
ERROR: GET /workspace/1/link admin
ERROR: PUT /workspace/1/variables admin
[31/07/2008 12:32:56] no se pudieron actualizar las variablesWorkSpaceVariable matching query does not exist.
ERROR: GET /workspace/1/link [Anónimo]
[01/08/2008 12:02:24] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 197, in cloneTuple
    self.update_foreign_keys(cloned_tuple, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 120, in update_foreign_keys
    for pending_fk in pending_fks:
TypeError: 'NoneType' object is not iterable

ERROR: GET /workspace/1/link [Anónimo]
[01/08/2008 12:03:28] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 227, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 194, in cloneTuple
    self.mark_pending_fk(linker_table, linker_field, linker_tuple_id, referenced_table, referenced_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 138, in mark_pending_fk
    this.pendingFks.addPending(linker_table, linker_field, linker_tuple_id, referenced_table, referenced_tuple)
NameError: global name 'this' is not defined

ERROR: GET /workspace/1/link [Anónimo]
[01/08/2008 12:05:23] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 92, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 459, in read
    packageManager.cloneTuple(workspace)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 227, in cloneTuple
    self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 204, in cloneTuple
    cloned_related_tuple = self.cloneTuple(related_tuple)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 197, in cloneTuple
    self.update_foreign_keys(cloned_tuple, tuple.id)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/packageManager.py", line 131, in update_foreign_keys
    exec(stm)
  File "<string>", line 1
    linker_tuple.abstract_variable=cloned_tuple)
                                               ^
SyntaxError: unexpected EOF while parsing

ERROR: PUT /workspace/1/variables [Anónimo]
[01/08/2008 13:40:03] Traceback (most recent call last):
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 65, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/resource.py", line 109, in dispatch
    return target.update(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/django/db/transaction.py", line 194, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/eclipse/workspace/EzWebTrunk/workspace/views.py", line 406, in update
    user = get_user_authentication(request)
  File "/home/mac/eclipse/workspace/EzWebTrunk/commons/authentication.py", line 57, in get_user_authentication
    raise Http403 (_("You must be logged"))
Http403: Debe registrarse

ERROR: PUT /workspace/10/variables admin
[27/11/2008 18:41:07] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 18:41:45] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 18:44:45] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 18:45:10] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 18:46:21] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:00:20] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:00:40] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:01:32] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:02:40] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:06:32] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:07:46] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:11:26] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:12:36] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: PUT /workspace/10/variables admin
[27/11/2008 19:14:35] no se pudieron actualizar las variablesERROR:  el valor null para la columna «value» viola la restricción not null

UPDATE "workspace_variablevalue" SET "user_id" = 1, "value" = NULL, "abstract_variable_id" = 94 WHERE "workspace_variablevalue"."id" = 80 
ERROR: GET /user/admin/gadgets admin
[01/12/2008 11:34:52] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/gadget/views.py", line 60, in read
    data = serializers.serialize('python', gadgets, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 160, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna gadget_xhtml.content_type
LINE 1: ...ri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xh...
                                                             ^

SELECT "gadget_xhtml"."id", "gadget_xhtml"."uri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xhtml"."content_type" FROM "gadget_xhtml" WHERE "gadget_xhtml"."id" = 48 

ERROR: GET /workspaces/282 admin
ERROR: GET /user/admin/gadgets admin
[01/12/2008 11:35:26] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/gadget/views.py", line 60, in read
    data = serializers.serialize('python', gadgets, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 160, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna gadget_xhtml.content_type
LINE 1: ...ri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xh...
                                                             ^

SELECT "gadget_xhtml"."id", "gadget_xhtml"."uri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xhtml"."content_type" FROM "gadget_xhtml" WHERE "gadget_xhtml"."id" = 48 

ERROR: GET /workspaces/282 admin
ERROR: GET /user/admin/gadgets admin
[01/12/2008 11:35:47] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/gadget/views.py", line 60, in read
    data = serializers.serialize('python', gadgets, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 160, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna gadget_xhtml.content_type
LINE 1: ...ri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xh...
                                                             ^

SELECT "gadget_xhtml"."id", "gadget_xhtml"."uri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xhtml"."content_type" FROM "gadget_xhtml" WHERE "gadget_xhtml"."id" = 48 

ERROR: GET /workspaces/282 admin
ERROR: GET /workspaces/285 miguel
ERROR: GET /user/admin/gadgets admin
[01/12/2008 12:56:42] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/gadget/views.py", line 60, in read
    data = serializers.serialize('python', gadgets, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 47, in serialize
    self.handle_fk_field(obj, field)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/python.py", line 41, in handle_fk_field
    related = getattr(obj, field.name)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/fields/related.py", line 248, in __get__
    rel_obj = QuerySet(self.field.rel.to).get(**params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 160, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna gadget_xhtml.content_type
LINE 1: ...ri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xh...
                                                             ^

SELECT "gadget_xhtml"."id", "gadget_xhtml"."uri", "gadget_xhtml"."code", "gadget_xhtml"."url", "gadget_xhtml"."content_type" FROM "gadget_xhtml" WHERE "gadget_xhtml"."id" = 48 

ERROR: GET /workspaces/282 admin
[01/12/2008 12:56:42] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/workspace/views.py", line 273, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/workspace/EzWeb/commons/get_data.py", line 374, in get_global_workspace_data
    filter_data = serializers.serialize('python', filters, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 38, in serialize
    for obj in queryset:
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 185, in _result_iter
    self._fill_cache()
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 618, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la relación «connectable_filter»

SELECT "connectable_filter"."id", "connectable_filter"."name", "connectable_filter"."code", "connectable_filter"."label", "connectable_filter"."nature", "connectable_filter"."category", "connectable_filter"."help_text", "connectable_filter"."params" FROM "connectable_filter"

ERROR: GET /workspaces/290 anonymous1228132627154
[01/12/2008 12:57:09] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/workspace/views.py", line 273, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/mac/workspace/EzWeb/commons/get_data.py", line 374, in get_global_workspace_data
    filter_data = serializers.serialize('python', filters, ensure_ascii=False)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/core/serializers/base.py", line 38, in serialize
    for obj in queryset:
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 185, in _result_iter
    self._fill_cache()
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 618, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/query.py", line 275, in iterator
    for row in self.query.results_iter():
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/models/sql/query.py", line 1734, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la relación «connectable_filter»

SELECT "connectable_filter"."id", "connectable_filter"."name", "connectable_filter"."code", "connectable_filter"."label", "connectable_filter"."nature", "connectable_filter"."category", "connectable_filter"."help_text", "connectable_filter"."params" FROM "connectable_filter"

ERROR: GET /workspace/1/add anonymous1228132703184
[01/12/2008 13:05:53] Traceback (most recent call last):
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/mac/workspace/EzWeb/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/usr/lib/python2.5/site-packages/Django-1.0.2_final-py2.5.egg/django/db/transaction.py", line 238, in _commit_on_success
    res = func(*args, **kw)
  File "/home/mac/workspace/EzWeb/workspace/views.py", line 523, in read
    linkWorkspace(user, cloned_workspace.id)
  File "/home/mac/workspace/EzWeb/workspace/views.py", line 203, in linkWorkspace
    packageLinker.link_workspace(workspace, user)
  File "/home/mac/workspace/EzWeb/workspace/packageLinker.py", line 46, in link_workspace
    ws_igadgets = IGadget.objects.filter(tab__workspace=workspace)
NameError: global name 'IGadget' is not defined

ERROR: PUT /workspace/1/variables admin
[01/12/2008 15:17:39] no se pudieron actualizar las variablesWorkSpaceVariable matching query does not exist.
ERROR: GET /workspaces/5 anonymous1228380968164
[04/12/2008 09:56:12] Traceback (most recent call last):
  File "/home/imunoz/src/ezweb/trunk/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/imunoz/src/ezweb/trunk/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/imunoz/src/ezweb/trunk/workspace/views.py", line 273, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/imunoz/src/ezweb/trunk/commons/get_data.py", line 356, in get_global_workspace_data
    igadget_data = serializers.serialize('python', igadgets, ensure_ascii=False)
  File "/usr/local/lib/python2.5/site-packages/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python2.5/site-packages/django/core/serializers/base.py", line 38, in serialize
    for obj in queryset:
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 179, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 612, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 269, in iterator
    for row in self.query.results_iter():
  File "/usr/local/lib/python2.5/site-packages/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.5/site-packages/django/db/models/sql/query.py", line 1723, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.5/site-packages/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.5/site-packages/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna igadget_igadget.layout
LINE 1: ...igadget"."gadget_id", "igadget_igadget"."tab_id", "igadget_i...
                                                             ^

SELECT "igadget_igadget"."id", "igadget_igadget"."name", "igadget_igadget"."gadget_id", "igadget_igadget"."tab_id", "igadget_igadget"."layout", "igadget_igadget"."position_id" FROM "igadget_igadget" WHERE "igadget_igadget"."tab_id" = 5  ORDER BY "igadget_igadget"."id" ASC

ERROR: GET /workspaces/1 admin
[04/12/2008 09:59:49] Traceback (most recent call last):
  File "/home/imunoz/src/ezweb/trunk/commons/resource.py", line 59, in __call__
    return self.dispatch(request, self, *args, **kwargs)
  File "/home/imunoz/src/ezweb/trunk/commons/resource.py", line 86, in dispatch
    return target.read(request, *args, **kwargs)
  File "/home/imunoz/src/ezweb/trunk/workspace/views.py", line 273, in read
    workspace_data = get_global_workspace_data(data[0], workspaces[0], concept_data, user)
  File "/home/imunoz/src/ezweb/trunk/commons/get_data.py", line 356, in get_global_workspace_data
    igadget_data = serializers.serialize('python', igadgets, ensure_ascii=False)
  File "/usr/local/lib/python2.5/site-packages/django/core/serializers/__init__.py", line 86, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python2.5/site-packages/django/core/serializers/base.py", line 38, in serialize
    for obj in queryset:
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 179, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 612, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.5/site-packages/django/db/models/query.py", line 269, in iterator
    for row in self.query.results_iter():
  File "/usr/local/lib/python2.5/site-packages/django/db/models/sql/query.py", line 206, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.5/site-packages/django/db/models/sql/query.py", line 1723, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.5/site-packages/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.5/site-packages/django/db/backends/postgresql/base.py", line 52, in execute
    return self.cursor.execute(smart_str(sql, self.charset), self.format_params(params))
ProgrammingError: ERROR:  no existe la columna igadget_igadget.layout
LINE 1: ...igadget"."gadget_id", "igadget_igadget"."tab_id", "igadget_i...
                                                             ^

SELECT "igadget_igadget"."id", "igadget_igadget"."name", "igadget_igadget"."gadget_id", "igadget_igadget"."tab_id", "igadget_igadget"."layout", "igadget_igadget"."position_id" FROM "igadget_igadget" WHERE "igadget_igadget"."tab_id" = 1  ORDER BY "igadget_igadget"."id" ASC

